/** 한국 포함 대표적인 30개 국가 (회원가입·프로필 편집 공통) */
export const COUNTRY_OPTIONS = [
  { value: 'KR', label: '대한민국' },
  { value: 'US', label: '미국' },
  { value: 'JP', label: '일본' },
  { value: 'CN', label: '중국' },
  { value: 'GB', label: '영국' },
  { value: 'DE', label: '독일' },
  { value: 'FR', label: '프랑스' },
  { value: 'CA', label: '캐나다' },
  { value: 'AU', label: '호주' },
  { value: 'IT', label: '이탈리아' },
  { value: 'ES', label: '스페인' },
  { value: 'IN', label: '인도' },
  { value: 'BR', label: '브라질' },
  { value: 'RU', label: '러시아' },
  { value: 'VN', label: '베트남' },
  { value: 'TH', label: '태국' },
  { value: 'SG', label: '싱가포르' },
  { value: 'MY', label: '말레이시아' },
  { value: 'PH', label: '필리핀' },
  { value: 'ID', label: '인도네시아' },
  { value: 'NL', label: '네덜란드' },
  { value: 'SE', label: '스웨덴' },
  { value: 'CH', label: '스위스' },
  { value: 'MX', label: '멕시코' },
  { value: 'PL', label: '폴란드' },
  { value: 'TR', label: '터키' },
  { value: 'SA', label: '사우디아라비아' },
  { value: 'AE', label: '아랍에미리트' },
  { value: 'ETC', label: '기타' },
] as const;
